#ifndef VERSION_H
#define VERSION_H

#define PROJECT_VERSION_MAJOR 20
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 0
#define PROJECT_VERSION_STRING "20.0.0-blu-irq"

#endif // VERSION_H
