#ifndef VERSION_H
#define VERSION_H

#define PROJECT_VERSION_MAJOR 19
#define PROJECT_VERSION_MINOR 1
#define PROJECT_VERSION_PATCH 11
#define PROJECT_VERSION_STRING "19.1.11-blu"

#endif // VERSION_H
